/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba1_b2;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESFOT
 */
public class TiendaFrutas extends javax.swing.JFrame {

    /**
     * Creates new form TiendaFrutas
     */
    
    String [][] frutas;
    String [][] clientes;
    DefaultTableModel tblModelFrutas;
    DefaultTableModel tblModelCliente;
    
    List<Fruta> listaFrutas = new ArrayList<Fruta>();
    DefaultComboBoxModel listaFrutasModel = new DefaultComboBoxModel(listaFrutas.toArray());
    
    public TiendaFrutas() {
        initComponents();
        //*********************   Tabla para Materias *********************
         String titulosColumnasFrutas [] = new String []{
            "Cliente","Cedula","Fruta","Precio"       
        };
        tblModelFrutas = new DefaultTableModel(frutas, titulosColumnasFrutas);
        tblRegistroFrutas.setModel(tblModelFrutas);
        
        //*********************   Tabla para Clientes *********************
         String titulosColumnasCliente [] = new String []{
            "Nombre","Cedula"   
        };
        tblModelCliente = new DefaultTableModel(clientes, titulosColumnasFrutas);
        tblCliente.setModel(tblModelCliente);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lblNombreClien = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblTituloCliente = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRegistroFrutas = new javax.swing.JTable();
        btnSeleccionarFru = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblTituloCliente1 = new javax.swing.JLabel();
        lblListaFrutas = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombreFru = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        cmbListaFrutas = new javax.swing.JComboBox<>();
        txtCodigoFru = new javax.swing.JTextField();
        txtNombreFru = new javax.swing.JTextField();
        txtPrecioFru = new javax.swing.JTextField();
        btnAñadirFruta = new javax.swing.JButton();
        btnRegistrarPedido = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lblTituloPedido = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        cmbListaCedula = new javax.swing.JComboBox<>();
        lblListaCedula = new javax.swing.JLabel();
        lblFacultad7 = new javax.swing.JLabel();
        lblFacultad8 = new javax.swing.JLabel();
        btnMostrarPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreClien.setText("Nombre:");

        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });

        lblTituloCliente.setText("Cliente");

        tblRegistroFrutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblRegistroFrutas);

        btnSeleccionarFru.setText("OK");
        btnSeleccionarFru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarFruActionPerformed(evt);
            }
        });

        lblCedula.setText("Cedula:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        lblTituloCliente1.setText("Fruta");

        lblListaFrutas.setText("Lista de frutas:");

        lblCodigo.setText("Código:");

        lblNombreFru.setText("Nombre:");

        lblPrecio.setText("Precio:");

        cmbListaFrutas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manzana", "Pera", "Uva", "Durazno", "Sandia " }));

        txtCodigoFru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoFruActionPerformed(evt);
            }
        });

        txtNombreFru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreFruActionPerformed(evt);
            }
        });

        txtPrecioFru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioFruActionPerformed(evt);
            }
        });

        btnAñadirFruta.setText("Añadir fruta al pedido");
        btnAñadirFruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirFrutaActionPerformed(evt);
            }
        });

        btnRegistrarPedido.setText("Registrar Pedido");
        btnRegistrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblTituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNombreClien, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedula)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeleccionarFru, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAñadirFruta)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreFru, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreFru, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoFru, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioFru, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnRegistrarPedido))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreClien)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListaFrutas)
                    .addComponent(cmbListaFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarFru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoFru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFru)
                    .addComponent(txtNombreFru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecioFru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnAñadirFruta)
                .addGap(5, 5, 5)
                .addComponent(btnRegistrarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar", jPanel4);

        lblTituloPedido.setText("PEDIDOS REGISTRADOS");

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblCliente);

        cmbListaCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbListaCedula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbListaCedulacmbListaCedulasItemStateChanged(evt);
            }
        });

        lblListaCedula.setText("Lista de cedulas:");

        lblFacultad7.setText("INFORMACION DEL CLIENTE:");

        lblFacultad8.setText("PEDIDOS DEL CLIENTE:");

        btnMostrarPedidos.setText("Mostrar pedido");
        btnMostrarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblTituloPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblListaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbListaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnMostrarPedidos))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFacultad7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(lblFacultad8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTituloPedido)
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListaCedula)
                    .addComponent(cmbListaCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarPedidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultad7)
                    .addComponent(lblFacultad8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jTabbedPane1.addTab("MostrarPedidos", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListaCedulacmbListaCedulasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbListaCedulacmbListaCedulasItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbListaCedulacmbListaCedulasItemStateChanged

    private void txtPrecioFruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioFruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioFruActionPerformed

    private void txtNombreFruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreFruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFruActionPerformed

    private void txtCodigoFruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoFruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFruActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnSeleccionarFruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFruActionPerformed

        String frutaSel = cmbListaFrutas.getSelectedItem().toString();
        //Fruta newFruta = new Fruta (" "," "," ");
        if (frutaSel == "Manzana"){
            txtCodigoFru.setText("001a");
            txtCodigoFru.getText();
            txtNombreFru.setText(cmbListaFrutas.getSelectedItem().toString());
            txtNombreFru.getText();
            txtPrecioFru.setText("0,30");
            txtPrecioFru.getText();
            //newFruta = new Fruta (codigo,nombre,precio);
        }else if (frutaSel == "Pera"){
            txtCodigoFru.setText("012b");
            txtCodigoFru.getText();
            txtNombreFru.setText(cmbListaFrutas.getSelectedItem().toString());
            txtNombreFru.getText();
            txtPrecioFru.setText("0,25");
            txtPrecioFru.getText();
            //newFruta = new Fruta (codigo,nombre,precio);
        }else if (frutaSel == "Uva"){
            txtCodigoFru.setText("023c");
            txtCodigoFru.getText();
            txtNombreFru.setText(cmbListaFrutas.getSelectedItem().toString());
            txtNombreFru.getText();
            txtPrecioFru.setText("0,05");
            txtPrecioFru.getText();
            //newFruta = new Fruta (codigo,nombre,precio);
        }else if (frutaSel == "Durazno"){
            txtCodigoFru.setText("034d");
            txtCodigoFru.getText();
            txtNombreFru.setText(cmbListaFrutas.getSelectedItem().toString());
            txtNombreFru.getText();
            txtPrecioFru.setText("0,55");
            txtPrecioFru.getText();
            //newFruta = new Fruta (codigo,nombre,precio);
        }else if (frutaSel == "Sandia"){
            txtCodigoFru.setText("043c");
            txtCodigoFru.getText();
            txtNombreFru.setText(cmbListaFrutas.getSelectedItem().toString());
            txtNombreFru.getText();
            txtPrecioFru.setText("2,50");
            txtPrecioFru.getText();
            //newFruta = new Fruta (codigo,nombre,precio);
        }

        //listaFrutas.add(newFruta);
        //tblModelFrutas.addRow(new String [] {newFruta.getCodigo(),newFruta.getNombre(),newFruta.getPrecio()});
    }//GEN-LAST:event_btnSeleccionarFruActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btnAñadirFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirFrutaActionPerformed
        // TODO add your handling code here:
        String codigo=txtCodigoFru.getText();
        String nombre=txtNombreFru.getText();
        String precio=txtPrecioFru.getText();
        
        String nombreClien=txtNombreCliente.getText();
        String cedulaCliente=txtCedula.getText();

        Fruta newFruta = new Fruta (codigo, nombre, precio);
        
        if (!nombreClien.equals("")&& !cedulaCliente.equals("")){
            int confirmacion= JOptionPane.showConfirmDialog(rootPane, "Estás seguro?","Confirmación",JOptionPane.YES_NO_OPTION);
            if(confirmacion ==0){
                //listaFrutas.add(newFruta);
                //tblModelFrutas.addRow(new String [] {newFruta.getCodigo(),newFruta.getNombre(),newFruta.getPrecio()});
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar todos los campos");
        }
        
    }//GEN-LAST:event_btnAñadirFrutaActionPerformed

    private void btnRegistrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPedidoActionPerformed
        // TODO add your handling code here:
        String nombreClien=txtNombreCliente.getText();
        String cedulaClien=txtCedula.getText();
        //******************Registramos datos Cliente******************
        Cliente newCliente = new Cliente (nombreClien,cedulaClien);
        String codigo=txtCodigoFru.getText();
        String nombre=txtNombreFru.getText();
        String precio=txtPrecioFru.getText();
        
        //******************Registramos datos de la fruta******************
        Fruta newFruta = new Fruta (codigo, nombre, precio);
        if (!nombreClien.equals("")&& !cedulaClien.equals("")&& !codigo.equals("")){
            int confirmacion= JOptionPane.showConfirmDialog(rootPane, "Estás seguro?","Confirmación",JOptionPane.YES_NO_OPTION);
            if(confirmacion ==0){
                listaFrutas.add(newFruta);
                tblModelFrutas.addRow(new String [] {nombreClien,cedulaClien,newFruta.getNombre(),newFruta.getPrecio()});
                cmbListaCedula.addItem(cedulaClien);
                txtNombreCliente.setText("");
                txtCedula.setText("");
                txtCodigoFru.setText("");
                txtNombreFru.setText("");
                txtPrecioFru.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar todos los campos");
        }
        
        
        
    }//GEN-LAST:event_btnRegistrarPedidoActionPerformed

    private void btnMostrarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPedidosActionPerformed
        // TODO add your handling code here:
        
        String clienteCedula =  cmbListaCedula.getSelectedItem().toString();
        
        for (int i = 0; i < tblModelFrutas.getRowCount(); i++) {
            if (clienteCedula  == tblModelFrutas.getValueAt(i, 1).toString().trim() ){
                tblModelCliente.addRow(new String [] {clienteCedula});    
                       
            }
                    
        }   
        
    }//GEN-LAST:event_btnMostrarPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiendaFrutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiendaFrutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirFruta;
    private javax.swing.JButton btnMostrarPedidos;
    private javax.swing.JButton btnRegistrarPedido;
    private javax.swing.JButton btnSeleccionarFru;
    private javax.swing.JComboBox<String> cmbListaCedula;
    private javax.swing.JComboBox<String> cmbListaCedulas;
    private javax.swing.JComboBox<String> cmbListaCedulas1;
    private javax.swing.JComboBox<String> cmbListaFrutas;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFacultad1;
    private javax.swing.JLabel lblFacultad2;
    private javax.swing.JLabel lblFacultad3;
    private javax.swing.JLabel lblFacultad4;
    private javax.swing.JLabel lblFacultad7;
    private javax.swing.JLabel lblFacultad8;
    private javax.swing.JLabel lblListaCedula;
    private javax.swing.JLabel lblListaCedulas;
    private javax.swing.JLabel lblListaCedulas1;
    private javax.swing.JLabel lblListaFrutas;
    private javax.swing.JLabel lblNombreClien;
    private javax.swing.JLabel lblNombreFru;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTituloCliente;
    private javax.swing.JLabel lblTituloCliente1;
    private javax.swing.JLabel lblTituloPedido;
    private javax.swing.JLabel lblTituloPedidos;
    private javax.swing.JLabel lblTituloPedidos1;
    private javax.swing.JTable tblCargoEspecifico;
    private javax.swing.JTable tblCargoEspecifico1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblRegistroFrutas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigoFru;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreFru;
    private javax.swing.JTextField txtPrecioFru;
    // End of variables declaration//GEN-END:variables
}
